services:
  - type: web
    name: guardian-relacional
    runtime: docker
    region: frankfurt # O 'oregon' seg√∫n tu preferencia
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 8080
      - key: BIND_HOST
        value: 0.0.0.0
      - key: RUST_LOG
        value: info
      - key: MAX_FILE_BYTES
        value: 10485760 # 10 MB
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_API_KEY
        sync: false # Esto indica que debes poner la clave manualmente en el dashboard de Render por seguridad